apiToken: ""

image: registry.okmeter.io/agent/okagent:latest

config:
  # Your custom YAML config here

resources:
  requests:
    memory: 100Mi
    cpu: 100m
  limits:
    memory: 2Gi

tolerations:
- operator: Exists
