apiToken: ""

image: registry.okmeter.io/agent/okagent:latest

config:
  # Your custom YAML config here

resources:
  requests:
    memory: 100Mi
    cpu: 100m
  limits:
    memory: 2Gi

tolerations:
- operator: Exists

rds:
  enable: false
  persistentVolume:
    # recommend to use PVC for okagent for prevent lost metrics. By default used emptyDir
    enable: false 
    storageClass: ""
    size: 1Gi
  config: {}
#    plugin: postgresql # or mysql
#    source_hostname: "some uniq name" # this name will be displayd on host page in okmeter. Name must be uniq
#    config:
#      host: x.x.x.x # database IP addres
#      user: okagent # user for connect to database
#      password: yyy # passwort for connect to database
#      port: 5432 # port if use not standart port 
