---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
data:
{{- range $file, $data := required "You have to define at least one RDS configuration in values.yaml" .Values.rdsConfigs }}
  {{ $file }}: {{ $data | toYaml | b64enc }}
{{- end }}
