---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }} 
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: [get, list, watch]
  - nonResourceURLs: ['*']
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }} 
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }} 
  namespace: {{ .Release.Namespace }} 

