{{- if ne .Values.rds.enable true }}
{{- if .Values.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
{{- end }}
{{- end }}
